version: '3.9'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    command: >
      sh -c "python manage.py migrate &&
             gunicorn DawaFasta.wsgi:application --bind 0.0.0.0:$PORT"
    ports:
      - 8000:8000
    depends_on:
      - migrations

  migrations:
    build:
      context: .
      dockerfile: Dockerfile
    command: python manage.py migrate

volumes:
  static:
